// <auto-generated>
//  Generated by tools/extract_slideok.py — DO NOT EDIT BY HAND.
//  Re-run the script after modifying any Slide_*/Star_* prefab.
// </auto-generated>
#nullable enable

using System.Collections.Generic;

/// <summary>
/// SlideOK (Just_str/Just_curv) 位姿(localX/localY/eulerZ)静态表，按 slide shape 检索。
/// 由 tools/extract_slideok.py 从 Assets/SlidePrefab/*.prefab 一次性抽取。
/// 镜像/翻转在运行时计算（见 SlideDrop.Init），不在表里预存翻转副本。
/// </summary>
public static class SlideOKTable
{
    public readonly struct OKPose
    {
        public readonly float X, Y, RotZ;
        public OKPose(float x, float y, float rotZ) { X = x; Y = y; RotZ = rotZ; }
    }

    private static readonly Dictionary<string, OKPose> _map = new()
    {
        ["L2"] = new OKPose(2.250767f, 1.728999f, 0.000000f),
        ["L3"] = new OKPose(2.543001f, -1.188000f, -22.713001f),
        ["L4"] = new OKPose(0.219028f, -2.970532f, -45.245003f),
        ["L5"] = new OKPose(-2.710768f, -2.611632f, -68.288000f),
        ["circle1"] = new OKPose(0.044000f, 4.645000f, 0.000000f),
        ["circle2"] = new OKPose(3.260000f, 3.260000f, -45.000004f),
        ["circle3"] = new OKPose(4.640000f, -0.010000f, -90.000010f),
        ["circle4"] = new OKPose(3.250000f, -3.300000f, -135.000000f),
        ["circle5"] = new OKPose(-0.040000f, -4.650000f, -180.000020f),
        ["circle6"] = new OKPose(-3.310000f, -3.240000f, -225.000000f),
        ["circle7"] = new OKPose(-4.620000f, 0.070000f, 90.000010f),
        ["circle8"] = new OKPose(-3.240000f, 3.290000f, -315.000000f),
        ["line3"] = new OKPose(3.450000f, 0.200000f, -67.353004f),
        ["line4"] = new OKPose(1.700000f, -2.430000f, -90.000010f),
        ["line5"] = new OKPose(-1.080000f, -2.300000f, -112.795006f),
        ["line6"] = new OKPose(-3.120000f, -0.320000f, -135.000000f),
        ["line7"] = new OKPose(-2.398000f, 2.752000f, -157.059000f),
        ["ppqq1"] = new OKPose(3.190000f, 2.620000f, 123.461006f),
        ["ppqq2"] = new OKPose(4.564000f, -0.344000f, 449.328000f),
        ["ppqq3"] = new OKPose(2.590000f, -2.310000f, 10.680000f),
        ["ppqq4"] = new OKPose(0.790000f, -2.470000f, -66.121000f),
        ["ppqq5"] = new OKPose(-1.210000f, -2.360000f, -110.109010f),
        ["ppqq6"] = new OKPose(-2.657000f, -0.513000f, 214.171000f),
        ["ppqq7"] = new OKPose(-2.472000f, 2.055000f, 182.646000f),
        ["ppqq8"] = new OKPose(0.222000f, 3.547000f, 154.018000f),
        ["pq1"] = new OKPose(1.974722f, 2.261541f, 90.000010f),
        ["pq2"] = new OKPose(3.028000f, 0.252000f, 45.000004f),
        ["pq3"] = new OKPose(2.345000f, -1.956000f, 0.000000f),
        ["pq4"] = new OKPose(0.296626f, -3.064554f, -45.000004f),
        ["pq5"] = new OKPose(-1.972909f, -2.402302f, -90.000010f),
        ["pq6"] = new OKPose(-2.921237f, -0.147015f, -135.000000f),
        ["pq7"] = new OKPose(-2.218574f, 1.944000f, -180.000020f),
        ["pq8"] = new OKPose(-0.203000f, 2.983000f, 135.341000f),
        ["s"] = new OKPose(-0.610000f, -3.030000f, -134.388000f),
        ["v1"] = new OKPose(1.220000f, 2.630000f, 67.500000f),
        ["v2"] = new OKPose(2.370000f, 0.850000f, 23.029001f),
        ["v3"] = new OKPose(2.310000f, -1.150000f, -21.368002f),
        ["v4"] = new OKPose(0.920000f, -2.450000f, -67.284004f),
        ["v6"] = new OKPose(-2.440000f, -0.920000f, -155.866010f),
        ["v7"] = new OKPose(-2.300000f, 1.110000f, 158.528020f),
        ["v8"] = new OKPose(-0.840000f, 2.350000f, 113.213005f),
        ["wifi"] = new OKPose(-1.610000f, -3.870000f, 157.430010f),
    };

    /// <summary>取出指定形状的 slideOK 位姿。返回 null 表示未知形状。</summary>
    public static OKPose? Get(string shape) => _map.TryGetValue(shape, out var pose) ? pose : null;

    /// <summary>是否包含此 shape。</summary>
    public static bool Contains(string shape) => _map.ContainsKey(shape);
}
